# Add problems directories
add_subdirectory(AckleyHard_GMADS)
add_subdirectory(Beale_GMADS)
add_subdirectory(Branin_GMADS)
add_subdirectory(Bukin6_GMADS)
add_subdirectory(EVD2_GMADS)
add_subdirectory(GoldsteinPrice1_GMADS)
add_subdirectory(GoldsteinPrice2_GMADS)
add_subdirectory(HS78_GMADS)
add_subdirectory(Rastragin_GMADS)
add_subdirectory(RosenbrockMixed_GMADS)
add_subdirectory(RosenSuzuki_GMADS)
add_subdirectory(StyblinskiTang_GMADS)
add_subdirectory(Toy1_GMADS)
add_subdirectory(Toy2_GMADS)
add_subdirectory(Wong1_GMADS)
add_subdirectory(Zakharov_GMADS)
# Second batch of problems
add_subdirectory(Camel_GMADS)
add_subdirectory(EVD61_GMADS)
add_subdirectory(Gamma_GMADS)
add_subdirectory(Hal04_GMADS)
add_subdirectory(Hartmann_GMADS)
add_subdirectory(Ishigami_GMADS)
add_subdirectory(KowalikOsborne_GMADS)
add_subdirectory(Levy_GMADS)
add_subdirectory(McCormick_GMADS)
add_subdirectory(OET5_GMADS)
add_subdirectory(Roustant_GMADS)
add_subdirectory(Shekel_GMADS)
add_subdirectory(ThreeHumps_GMADS)
add_subdirectory(Wong3_GMADS)
